// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCmHBcaicQ7JogW0-TK9s0h3iotHamLQ',
    appId: '1:862880662876:web:534f49897b06ddc178ed99',
    messagingSenderId: '862880662876',
    projectId: 'prakflutterfirebase-6819c',
    authDomain: 'prakflutterfirebase-6819c.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-6819c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7VFN11h1yIQRtYFHUMSVAvQZejdWYss',
    appId: '1:862880662876:android:bb5e0b79a96b143e78ed99',
    messagingSenderId: '862880662876',
    projectId: 'prakflutterfirebase-6819c',
    storageBucket: 'prakflutterfirebase-6819c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtYxoWbsJtrTUnfPn9P-pTLKYRhiBX3Q',
    appId: '1:862880662876:ios:7bad3b84bccaac5278ed99',
    messagingSenderId: '862880662876',
    projectId: 'prakflutterfirebase-6819c',
    storageBucket: 'prakflutterfirebase-6819c.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYtYxoWbsJtrTUnfPn9P-pTLKYRhiBX3Q',
    appId: '1:862880662876:ios:7bad3b84bccaac5278ed99',
    messagingSenderId: '862880662876',
    projectId: 'prakflutterfirebase-6819c',
    storageBucket: 'prakflutterfirebase-6819c.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbCmHBcaicQ7JogW0-TK9s0h3iotHamLQ',
    appId: '1:862880662876:web:5cd826a0d7b04b3378ed99',
    messagingSenderId: '862880662876',
    projectId: 'prakflutterfirebase-6819c',
    authDomain: 'prakflutterfirebase-6819c.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-6819c.appspot.com',
  );

}